version: '3.3'

services:
    web:
        build:
           context: ./
           dockerfile: ./DockefileApache
        ports:
          - "80:80"
        volumes:
          - ../:/var/www/html/
        network_mode: "bridge"
    node:
      image: "node:12"
      command: "yarn encore dev --watch --watch-poll"
      working_dir: /var/www/html
      volumes:
        - ../:/var/www/html/:delegated
