version: '3.3'

services:
    web-barcode:
        build:
           context: ./
           dockerfile: ./DockefileApache
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ../:/var/www/html/:delegated
    node-barcode:
      image: "node:12"
      command: "yarn encore dev --watch --watch-poll"
      working_dir: /var/www/html
      volumes:
        - ../:/var/www/html/:delegated
